### PR TITLE
fix: make cargo happy

### LINKED ISSUE #1: Crate no longer compiles with 1.70.0-nightly
```
$ cargo +nightly version
cargo 1.70.0-nightly (15d090969 2023-03-21)
```

```
error[E0015]: cannot call non-const fn `Simd::<u8, 16>::splat` in constants
    --> /home/emerald/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bitsvec-0.1.1/src/lib.rs:1236:32
     |
1236 |             const ZERO: Self = <$type>::splat(0);
     |                                ^^^^^^^^^^^^^^^^^
...
1262 | impl_bitblock!(u8x16, u8, 16);
     | ----------------------------- in this macro invocation
     |
     = note: calls in constants are limited to constant functions, tuple structs and tuple variants
     = note: this error originates in the macro `impl_bitblock` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0015]: cannot call non-const fn `Simd::<u8, 16>::splat` in constants
    --> /home/emerald/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bitsvec-0.1.1/src/lib.rs:1237:31
     |
1237 |             const MAX: Self = <$type>::splat(<$item_type>::MAX);
     |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
1262 | impl_bitblock!(u8x16, u8, 16);
     | ----------------------------- in this macro invocation
     |
     = note: calls in constants are limited to constant functions, tuple structs and tuple variants
     = note: this error originates in the macro `impl_bitblock` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0015]: cannot call non-const fn `Simd::<u16, 8>::splat` in constants
    --> /home/emerald/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bitsvec-0.1.1/src/lib.rs:1236:32
     |
1236 |             const ZERO: Self = <$type>::splat(0);
     |                                ^^^^^^^^^^^^^^^^^
...
1263 | impl_bitblock!(u16x8, u16, 8);
     | ----------------------------- in this macro invocation
     |
     = note: calls in constants are limited to constant functions, tuple structs and tuple variants
     = note: this error originates in the macro `impl_bitblock` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0015]: cannot call non-const fn `Simd::<u16, 8>::splat` in constants
    --> /home/emerald/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bitsvec-0.1.1/src/lib.rs:1237:31
     |
1237 |             const MAX: Self = <$type>::splat(<$item_type>::MAX);
     |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
1263 | impl_bitblock!(u16x8, u16, 8);
     | ----------------------------- in this macro invocation
     |
     = note: calls in constants are limited to constant functions, tuple structs and tuple variants
     = note: this error originates in the macro `impl_bitblock` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0015]: cannot call non-const fn `Simd::<u32, 4>::splat` in constants
    --> /home/emerald/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bitsvec-0.1.1/src/lib.rs:1236:32
     |
1236 |             const ZERO: Self = <$type>::splat(0);
     |                                ^^^^^^^^^^^^^^^^^
...
1264 | impl_bitblock!(u32x4, u32, 4);
     | ----------------------------- in this macro invocation
     |
     = note: calls in constants are limited to constant functions, tuple structs and tuple variants
     = note: this error originates in the macro `impl_bitblock` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0015]: cannot call non-const fn `Simd::<u32, 4>::splat` in constants
    --> /home/emerald/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bitsvec-0.1.1/src/lib.rs:1237:31
     |
1237 |             const MAX: Self = <$type>::splat(<$item_type>::MAX);
     |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
1264 | impl_bitblock!(u32x4, u32, 4);
     | ----------------------------- in this macro invocation
     |
     = note: calls in constants are limited to constant functions, tuple structs and tuple variants
     = note: this error originates in the macro `impl_bitblock` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0015]: cannot call non-const fn `Simd::<u32, 8>::splat` in constants
    --> /home/emerald/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bitsvec-0.1.1/src/lib.rs:1236:32
     |
1236 |             const ZERO: Self = <$type>::splat(0);
     |                                ^^^^^^^^^^^^^^^^^
...
1265 | impl_bitblock!(u32x8, u32, 8);
     | ----------------------------- in this macro invocation
     |
     = note: calls in constants are limited to constant functions, tuple structs and tuple variants
     = note: this error originates in the macro `impl_bitblock` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0015]: cannot call non-const fn `Simd::<u32, 8>::splat` in constants
    --> /home/emerald/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bitsvec-0.1.1/src/lib.rs:1237:31
     |
1237 |             const MAX: Self = <$type>::splat(<$item_type>::MAX);
     |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
1265 | impl_bitblock!(u32x8, u32, 8);
     | ----------------------------- in this macro invocation
     |
     = note: calls in constants are limited to constant functions, tuple structs and tuple variants
     = note: this error originates in the macro `impl_bitblock` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0015]: cannot call non-const fn `Simd::<u64, 2>::splat` in constants
    --> /home/emerald/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bitsvec-0.1.1/src/lib.rs:1236:32
     |
1236 |             const ZERO: Self = <$type>::splat(0);
     |                                ^^^^^^^^^^^^^^^^^
...
1266 | impl_bitblock!(u64x2, u64, 2);
     | ----------------------------- in this macro invocation
     |
     = note: calls in constants are limited to constant functions, tuple structs and tuple variants
     = note: this error originates in the macro `impl_bitblock` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0015]: cannot call non-const fn `Simd::<u64, 2>::splat` in constants
    --> /home/emerald/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bitsvec-0.1.1/src/lib.rs:1237:31
     |
1237 |             const MAX: Self = <$type>::splat(<$item_type>::MAX);
     |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
1266 | impl_bitblock!(u64x2, u64, 2);
     | ----------------------------- in this macro invocation
     |
     = note: calls in constants are limited to constant functions, tuple structs and tuple variants
     = note: this error originates in the macro `impl_bitblock` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0015]: cannot call non-const fn `Simd::<u64, 4>::splat` in constants
    --> /home/emerald/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bitsvec-0.1.1/src/lib.rs:1236:32
     |
1236 |             const ZERO: Self = <$type>::splat(0);
     |                                ^^^^^^^^^^^^^^^^^
...
1267 | impl_bitblock!(u64x4, u64, 4);
     | ----------------------------- in this macro invocation
     |
     = note: calls in constants are limited to constant functions, tuple structs and tuple variants
     = note: this error originates in the macro `impl_bitblock` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0015]: cannot call non-const fn `Simd::<u64, 4>::splat` in constants
    --> /home/emerald/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bitsvec-0.1.1/src/lib.rs:1237:31
     |
1237 |             const MAX: Self = <$type>::splat(<$item_type>::MAX);
     |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
1267 | impl_bitblock!(u64x4, u64, 4);
     | ----------------------------- in this macro invocation
     |
     = note: calls in constants are limited to constant functions, tuple structs and tuple variants
     = note: this error originates in the macro `impl_bitblock` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0015]: cannot call non-const fn `Simd::<u64, 8>::splat` in constants
    --> /home/emerald/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bitsvec-0.1.1/src/lib.rs:1236:32
     |
1236 |             const ZERO: Self = <$type>::splat(0);
     |                                ^^^^^^^^^^^^^^^^^
...
1268 | impl_bitblock!(u64x8, u64, 8);
     | ----------------------------- in this macro invocation
     |
     = note: calls in constants are limited to constant functions, tuple structs and tuple variants
     = note: this error originates in the macro `impl_bitblock` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0015]: cannot call non-const fn `Simd::<u64, 8>::splat` in constants
    --> /home/emerald/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bitsvec-0.1.1/src/lib.rs:1237:31
     |
1237 |             const MAX: Self = <$type>::splat(<$item_type>::MAX);
     |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
1268 | impl_bitblock!(u64x8, u64, 8);
     | ----------------------------- in this macro invocation
     |
     = note: calls in constants are limited to constant functions, tuple structs and tuple variants
     = note: this error originates in the macro `impl_bitblock` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### PR DESCRIPTION
**Pull request by PsiACE**
cc @the-emerald Could you help review this PR?

Fixes: #1

### CODE REVIEW

**Comment by the-emerald** [comment]
LGTM, it compiles, passes tests, and the benchmark figures on my computer look similar to on in the readme - so I don't think there's any preformance regression!

**Comment by PsiACE** [comment]
> LGTM, it compiles, passes tests, and the benchmark figures on my computer look similar to on in the readme - so I don't think there's any preformance regression!

thanks
